version: '2'

services:

  web:
    build: .
    restart: always
    container_name: "web"
#    volumes:
#      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGO_PASSWORD
      - SECRET_KEY_BASE
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/fp


  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
#    volumes_from:
#    - data
    environment:
      - MONGO_USER=root
      - MONGO_DB=fp
      - MONGO_PASSWORD
    volumes:
      - data:/var/lib/mongodb


volumes:
  data:



   