version: '2'
services:

  webapi:
    build: .
    restart: always
    ports:
      - 80:3000
    depends_on:
      - mongo
    environment:
      - MONGO_PASSWORD
      - SECRET_KEY_BASE
      - NODE_ENV=production
      - NODE_LOG_TO_STDOUT=true


  mongo:
    image: mongo
    environment:
      - MONGO_USER=root
      - MONGO_DB=fp
      - MONGO_PASSWORD
